---
title: "preprocessing"
output: html_document
date: "2023-07-26"
---

```{r}
setwd("~/R_scripts")

library(ArchR)

addArchRThreads(threads = 6)
addArchRGenome("hg38")
```

## Loading the data 

```{r}
#Get Input Fragment Files
inputFiles <- getInputFiles("pbmc_10k")[1]
names(inputFiles) <- "PBMC_10k"

#Create Arrow Files (disabled here)
ArrowFiles <- "PBMC_10k.arrow" #createArrowFiles(inputFiles, force = TRUE)

#ArchRProject
proj <- ArchRProject(ArrowFiles)
```

## Filtering

by total counts, gene counts etc

plotting fragments distribution

```{r}
p1 <- plotFragmentSizes(ArchRProj = proj)
p1
```

calculating TSS score and other metrics 

```{r}
p1 <- plotFragmentSizes(ArchRProj = proj)
p2 <- plotTSSEnrichment(ArchRProj = proj)

# saving the plots
# plotPDF(p1,p2, name = "QC-Sample-FragSizes-TSSProfile.pdf", ArchRProj = projHeme1, addDOC = FALSE, width = 5, height = 5)

p1 | p2
```

plotting the distribution of TSS before filtering

```{r}
p <- ggPoint(
    x = df[,1], 
    y = df[,2], 
    colorDensity = TRUE,
    continuousSet = "sambaNight",
    xlabel = "Log10 Unique Fragments",
    ylabel = "TSS Enrichment",
    xlim = c(log10(500), quantile(df[,1], probs = 0.99)),
    ylim = c(0, quantile(df[,2], probs = 0.99))
) + geom_hline(yintercept = 4, lty = "dashed") + geom_vline(xintercept = 3, lty = "dashed")

p
```

after filtering 


```{r}
proj <- proj[proj$TSSEnrichment > 6 & proj$nFrags > 2500 & !is.na(proj$Gex_nUMI)]


p <- ggPoint(
    x = df[,1], 
    y = df[,2], 
    colorDensity = TRUE,
    continuousSet = "sambaNight",
    xlabel = "Log10 Unique Fragments",
    ylabel = "TSS Enrichment",
    xlim = c(log10(500), quantile(df[,1], probs = 0.99)),
    ylim = c(0, quantile(df[,2], probs = 0.99))
) + geom_hline(yintercept = 4, lty = "dashed") + geom_vline(xintercept = 3, lty = "dashed")

p
```

## Doublet removals

by total counts, gene counts etc

```{r}
proj <- addDoubletScores(proj)
proj <- filterDoublets(proj)
```

# Filtering out mitochondrial genes

```{r}

```